# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd74c9f56743ce6ea51d39a106c202757446cbb40c709ddeb02bc6da375e04c63bfc84ae3d5169cdcc895ab0de0a055192326d7f9bb78c6ed2d73df0c6315ee6

test:
  secret_key_base: c8e800bfb57f5ca070e599cd20b6dbdce71a7c0f665e43aefe02d31fc662444a8f9c073dbcf888250eea75ed09c9b63a8ca8622c9225055350ef9a27711554a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
